### ISSUE TITLE
How can I execute dash using a secondary aws key set?

### ISSUE THREAD

**Issue by yaochen** [jaws-framework/JAWS#277]
I have separate accounts for each env(dev, test, stage, prod). 

In my creds file I have:

[default]
[test]
[stage]
[prod]

Is there a way to allow dash to take a param of which keys to use?

**Comment by Nopik** [comment]
See `ADMIN_AWS_PROFILE` in `admin.env`

**Comment by yaochen** [comment]
hmm i did that but im getting access denied.

my aws/credentails has:

[default]
key 
access

[test]
key
access

before i ran "jaws dash" i updated "ADMIN_AWS_PROFILE=default" to "ADMIN_AWS_PROFILE=test"

is this not correct?

**Comment by shortjared** [comment]
@yaochen You could simply do something like...

`ADMIN_AWS_PROFILE=test jaws dash`

You can do this, because the admin.env is only loaded if the environment variable is not already defined for the process. https://github.com/jaws-framework/JAWS/blob/e1b850b7617ddf50ffc62bff11dc5279132d8940/lib/index.js#L28-L38

**Comment by yaochen** [comment]
@shortjared 

very helpful, thanks!
