### ISSUE TITLE
Windows needs Shell to be run as an Administrator for symlink to work

### ISSUE THREAD

**Issue by johnthillaye** [jaws-framework/JAWS#44]
I use Windows 7 at work, when trying to deploy my function, `jaws deploy` returned this error:

````
****** JAWS: Deploying your Lambda function to AWS Lambda.  This could take a few minutes...
fs.js:848
  return binding.symlink(preprocessSymlinkDestination(destination, type),
                 ^
Error: EPERM, operation not permitted
````

It turns out Windows needs Admin authentication for symlink to work.
I figured posting this as an issue would help people save some time debugging.

Best.

**Comment by hlesesne** [comment]
+1

**Comment by ac360** [comment]
Thanks for this.  We'll try to find away around this.

**Comment by ac360** [comment]
Update 8/13/15:  

We’re currently working on a document that outlines the specifications for JAWS v1.0.0.  

A proposed resolution to this issue in particular is included in that document.  

Today or tomorrow, we will share the document for everyone to comment on because your feedback is essential.

**Comment by ac360** [comment]
Fixed in JAWS v1.  No more symlinking!
