### ISSUE TITLE
Investigate simpler installation process

### ISSUE THREAD

**Issue by ashack293** [jaws-framework/JAWS#52]
I think it would be possible to automate some of the steps in the installation process. 

I could investigate this.

**Comment by callmeStriking** [comment]
+1

Separating `jaws-lib` and `jaws-cli` into separate repos seems like the way to go. The complication created by making two projects in the same repository (and the cluttered commit history that's created) could easily be avoided by splitting them.

**Comment by ac360** [comment]
Update 8/13/15:  

We’re currently working on a document that outlines the specifications for JAWS v1.0.0.  

A proposed resolution to this issue in particular is included in that document.  

Today or tomorrow, we will share the document for everyone to comment on because your feedback is essential.

**Comment by ac360** [comment]
Fixed in JAWS V1
