### ISSUE TITLE
[JAWS V1] jaws deploy --set-gateway

### ISSUE THREAD

**Issue by marvinosswald** [jaws-framework/JAWS#57]
Maybe I've missed it somewhere so pardon me if that's the case, but it would be nice to automatically add an API Endpoint to the AWS API Gateway. I have multiple ways in mind right know:

- Use a parameter in lambda.json to determine which resource and endpoint to use ~~as well as which http method to accept~~ e.g.:

```  
  {
      "endpoint": "users/signup"
  }
```
- Use your local directory structure, as it is right know. Problem is I didn't came to a good solution yet how to do that with the new module naming coming in 1.0.0. Would be the more convention over configuration way i think.
- Let's pass the endpoint url as parameter after `--set-gateway` , but thats more an additional option i suppose as it would be unnecessary to do it every time you deploy a function. 

Thoughts ? Generally as well as on `--set-gateway` ? 

Of course there would be more to cover AWS Api Gateway.. for example url embed variables for example:

```  
  {
      "endpoint": "users/show/{userId}"
  }
```

**Comment by ac360** [comment]
:+1: We're still working on this.  It's critical.  API Gateway is still in its infancy and automating API Gateway operations has been tough.

• There is no aws-sdk support for API Gateway, so we can't use that to create endpoints for people.
• The api-gateway-swagger-import-tool is a standalone java tool that people have to install and build locally before they can use it.  

The awsm.json (previously lambda.json) could definitely include API Gateway data.  I just put in the Google document that it should include a swagger snippet, since swagger is a powerful standard.  Perhaps when installing a module, it will fetch the module's swagger and add it to the project's main swagger.json like it does with CloudFormation templates.

**Comment by marvinosswald** [comment]
I see, so it seems like we have to wait until they get the API Gateway support covered. Only other think as an workaround I can think of would be phantom.js combined with an script which basically controls the web interface itself..BUT thats such a bad solution I wasn't even sure if i should suggest it :D

Regarding the api-gateway-swagger-import-tool I've gone through the source code, roughly, seems portable to js to me but I don't get if it would be enough to have it without the aws-sdk support for API Gateway ? They name AWS-CLI as an requirement,  it's available for Win/OSX/Linux but would be bad ux I guess to have user get that covered on there own.. Maybe we can replace the AWS-CLI requirement in the process of porting api-gateway-swagger-import-tool or maybe I'm missing something.

**Comment by ac360** [comment]
:+1:  I'd love to rebuild that swagger import tool.  Actually, there's probably better options, like a single API Gateway API route that you could upload it to.  Anyway, I've filed swagger import tool complaint directly with the AWS team and I'm hoping a better solution is coming soon.

**Comment by MatthewRayfield** [comment]
There isn't AWS-SDK support for API Gateway, but there seems to be an API for it: https://docs.aws.amazon.com/apigateway/api-reference/

**Comment by ac360** [comment]
API Gateway auto-deployment is in JAWS V1
